# Generated by Django 4.2 on 2023-12-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('price', models.CharField(max_length=10, verbose_name='price')),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('description', models.TextField(verbose_name='description')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.price')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
    ]
